// <auto-generated />
namespace Rent.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class AddedRequiredToCustomerIdAndCarIdToRentCar : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddedRequiredToCustomerIdAndCarIdToRentCar));
        
        string IMigrationMetadata.Id
        {
            get { return "202001242211574_AddedRequiredToCustomerIdAndCarIdToRentCar"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
